version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pg-rag
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: ayushsharma3131/spring-ai-rag:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-ai-rag-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ragdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - postgres

volumes:
  pgdata:
