spring:
  application:
    name: spring-ai-rag

  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres

  ai:
    google.genai:
      api-key: ${GEMINI_API_KEY}
      chat:
        options:
          model: gemini-3.8-flash
          temperature: 0.3
      embedding:
        api-key: ${GEMINI_API_KEY}
        text:
          options:
            dimensions: 1536
            model: gemini-embedding-001

    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        table-name: vector_store
        remove-existing-vector-store-table: false

server:
  port: 8080

logging:
  level:
    org.springframework.ai: INFO
